baseURL = "http://localhost:1313/"
title = "Joel Capitao"

theme = "coder-portfolio"

DefaultContentLanguage = "en"
summaryLength = "40"

paginate = 20

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsUseClasses = true

disqusShortname ="yourdiscussshortname"

[params]
    author = "Joel Capitao"
    description = "This is my garage, somewhere in the Internet, where I share you experience and thoughts."
    keywords = ""
    info = ""
    avatarurl = "images/avatar.jpg"

    hideCredits = true
    hideCopyright = false

    snsShare = true

    thumbnail = "images/tn.png"

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    langseparator = "|"

[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/JoelCapitao/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/JoelCapitao/"

[languages]
    [languages.en]
        languagecode = "en"
        languagename = "English"
        title = "Joel Capitao"

        [languages.en.params]
            author = "Joel Capitao"
            info = ""
            description = ""
            keywords = ""

        [languages.en.menu]
            [[languages.en.menu.main]]
                name = "About"
                weight = 1.0
                url = "en/about"

    [languages.fr]
        languagecode = "fr"
        languagename = "Français"
        title = "Joel Capitao"

        [languages.fr.params]
            author = "Joel Capitao"
            description = ""
            keywords = ""
            info = ""

        [languages.fr.menu]
            [[languages.fr.menu.main]]
                name = "A propos"
                weight = 1.0
                url = "fr/about"
