[build]
  publish = "public"
  command = "hugo --config=config.toml"

[context.production.environment]
  HUGO_VERSION = "0.52"
  HUGO_ENV = "netlify"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.52"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.52"
